import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { languages } from '../cadence/search/languages.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const domain = 'https://brandnamechanges.com';
const escape = s => s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const cta = `<div class="actions"><a class="button primary" href="https://play.google.com/store/apps/details?id=io.cadenceapp.mobile">Get Cadence on Google Play</a><a class="button" href="https://testflight.apple.com/join/RdX9wmAq">Join the iPhone &amp; iPad beta</a></div><p class="note">Android is available on Google Play. iPhone and iPad access is through TestFlight.</p>`;
const pages = [
 {slug:'songwriting-app', title:'Songwriting app for lyrics, voice memos & demos | Cadence', heading:'Keep the whole song together.', description:'Write lyrics, find rhymes, keep vocal takes and arrange a demo in Cadence, a songwriting app for Android, iPhone and iPad.', intro:'A line in Notes. A melody in Voice Memos. A beat somewhere else. Cadence brings the pieces into one song so you can keep writing.', image:'library.webp', alt:'Cadence song library with projects and individual songs', body:`
 <section class="content"><h2>A songwriting notebook with room to grow</h2><p>Start with a lyric, an imported recording or a new vocal take. Keep those ideas with the song they belong to. Projects help you group songs into an EP, album or collection without losing the individual drafts.</p><p>You do not need to start with a complete production. Capture the next line while it is fresh, then return to the same song to develop it.</p></section>
 <section class="content"><h2>Find a rhyme without leaving the page</h2><p>Rhyme highlighting helps you see patterns across a verse. The inspector lets you explore perfect rhymes, slant rhymes, multisyllabic matches and assonance as you revise. Syllable counts can help you compare lines; saying the words over your beat is still the test of how they flow.</p><p><a href="/cadence/rhyme-finder/">Try the free English rhyme finder</a> before installing.</p></section>
 <section class="content"><h2>From a draft to something you can hear</h2><p>Bring in a beat, loop the part you are writing to, and record takes alongside your words. Use Arrange to sketch the song structure, then open the DAW to position clips, balance tracks and work with effects.</p><p><a href="/cadence/springtime-showers/">See the Springtime Showers arrangement and DAW walkthrough.</a></p></section>
 <section class="content"><h2>Your account and recordings</h2><p>Cadence keeps recordings on your device unless you share them. Account sync and local audio are different: signing in on a second device does not automatically transfer every recording. Keep exports of important work.</p><p>Explore the app before choosing a plan. The purchase screen shows the available plans and current price for your store.</p></section>`},
 {slug:'rap-writing-app',title:'Rap writing app with rhymes, beats & vocal takes | Cadence',heading:'Write the bar. Hear the verse.',description:'Write rap lyrics with rhyme highlighting, syllable counts, beat loops and vocal takes in Cadence. Keep your words and performance in one workspace.',intro:'Stay with the beat while you work on the words. See the rhyme patterns, try another ending and record the delivery without moving the verse between apps.',image:'rhyme-families.webp',alt:'Cadence rhyme inspector beside highlighted lyrics',body:`
 <section class="content"><h2>Rhyme is sound, not spelling</h2><p>Perfect rhymes share their stressed vowel and following sounds. Slant rhymes leave room for a looser connection. Multisyllabic rhymes carry a match across more than one syllable. Each gives you a different choice when the obvious ending feels forced.</p><p>Cadence puts those choices beside your writing. Highlighting shows possible connections; your accent, delivery and intended meaning decide which ones belong.</p><p><a href="/cadence/rhyme-finder/">Explore perfect and multisyllabic English rhymes.</a></p></section>
 <section class="content"><h2>Write against the part of the beat that matters</h2><p>Set an A–B loop around the section you are working on. Keep the compact player beside the fullscreen editor, and use beat markers to return to a point you want to rehearse. You can try a line several ways without searching through the entire instrumental each time.</p></section>
 <section class="content"><h2>Check the delivery, not just the line length</h2><p>A syllable count gives you a reference, but two lines with the same count can land differently. Record a take and listen for the stressed words, breaths and spaces. Move from a written draft into Arrange and the DAW when you are ready to build a demo.</p><p><a href="/cadence/springtime-showers/">Watch a real Cadence song move into the DAW.</a></p></section>`},
 {slug:'voice-memos-to-lyrics',title:'Turn voice memos into editable lyrics | Cadence',heading:'Give that voice memo a next step.',description:'Import a voice memo into Cadence, transcribe it on device and develop it into lyrics, a song structure and a demo. A practical workflow for songwriters.',intro:'Bring a recorded idea into the same place as your lyrics. Listen, transcribe, correct the words and keep writing with the original take close by.',image:'transcribe.webp',alt:'Cadence audio take and transcription controls',body:`
 <section class="content"><h2>Bring in the recording</h2><ol class="prose-list"><li>On iPhone, open Voice Memos, choose the recording and use Share → Cadence. You can also import an audio file from within Cadence.</li><li>Open the take in its song and choose the transcription action. Keep the recording available on the device while it processes.</li><li>Review the transcript against the audio before using it as your working lyric.</li></ol><p>If Cadence is not visible in the share row, open More and add it to your favourites. Android sharing depends on the recording app; exporting an audio file and using Cadence’s import is another route.</p></section>
 <section class="content"><h2>A transcript is a starting point</h2><p>Transcription runs on device. Background music, sung or rapidly delivered words, quiet recordings and overlapping voices can reduce accuracy. Correct the transcript while listening to the take, then shape line breaks and sections around the performance.</p><p>This is particularly useful for a spoken lyric sketch. It is not a guarantee of a word-perfect transcript of a finished song.</p></section>
 <section class="content"><h2>Keep the idea moving</h2><p>After the words are on the page, use rhyme suggestions to explore alternatives, bring in a beat and record another take. The original recording stays part of the song rather than disappearing into a separate folder of unnamed memos.</p><p><a href="/cadence/songwriting-app/">Explore the full songwriting workflow.</a></p></section>`},
 {slug:'springtime-showers',title:'Springtime Showers: Arrange & DAW walkthrough | Cadence',heading:'Inside Springtime Showers.',description:'Watch Springtime Showers in Cadence: move from a song arrangement into a multitrack DAW and inspect vocal effects. Real app footage with practical steps.',intro:'A working song, shown inside Cadence. These captures follow Springtime Showers through arrangement and vocal effects, with a writing workflow you can use on your own track.',body:`
 <section class="content"><h2>Start with your lyric and take</h2><p>Open a song and bring in its lyric, beat and vocal ideas. If the starting point is a voice memo, transcribe it and correct the words against the recording. <a href="/cadence/voice-memos-to-lyrics/">Follow the import and transcription guide.</a></p><p>The clips below show the arrangement and DAW stages of Springtime Showers. They do not document its original transcription.</p></section>
 <section class="content"><h2>Shape the arrangement, then open the DAW</h2><p>Use Arrange to organise the song sections. Listen through their order before moving into the DAW, where the beat and vocal takes become clips you can work with on a timeline.</p><figure class="film"><video controls playsinline preload="none" poster="/assets/cadence/arrange-to-daw.webp"><source src="/assets/cadence/arrange-to-daw.mp4" type="video/mp4"></video><figcaption>Springtime Showers: arrangement to multitrack DAW. Recorded in Cadence; interface details may differ in newer builds.</figcaption></figure><p>If a DAW session already exists, read the replacement confirmation before rebuilding from Arrange. Preserve manual edits and exported versions you want to keep.</p></section>
 <section class="content"><h2>Listen to the vocal in context</h2><p>Open the channel and effects controls. Compare the processed sound with the dry vocal, then return to the whole mix. Changes that sound impressive in isolation may make a lyric less clear when the beat returns.</p><figure class="film"><video controls playsinline preload="none" poster="/assets/cadence/dry-wet.webp"><source src="/assets/cadence/dry-wet.mp4" type="video/mp4"></video><figcaption>Springtime Showers: DAW and vocal-effects controls. This capture demonstrates the interface, not an audio-quality comparison.</figcaption></figure></section>
 <section class="content"><h2>Try the same workflow with one of your ideas</h2><p>Choose one recording you want to finish. Put it with its lyric, decide where the hook belongs, and make a rough demo you can listen to away from the editor. A useful next version can tell you more than another week of isolated notes.</p></section>`},
 {slug:'rhyme-finder',title:'Free English rhyme finder & multisyllabic rhymes | Cadence',heading:'Find the next sound.',description:'Find English perfect rhymes and multisyllabic matches with Cadence’s free browser tool. No sign-in. Your search stays on your device.',intro:'Start with a word. Explore matching sounds. Keep the one that means what you want to say.',tool:true,body:`
 <section class="tool" aria-label="English rhyme finder"><noscript><p>Enable JavaScript to use the rhyme finder. The explanation and app links below remain available.</p></noscript><div id="tool-controls" hidden><form id="rhyme-form"><label for="language">Language<select id="language" name="language">${languages.map(l => `<option value="${l.id}">${l.label}${l.available ? "" : " — coming later"}</option>`).join("")}</select></label><label for="word">Word or phrase<input id="word" name="word" maxlength="60" placeholder="Try motion" required autocomplete="off" autocapitalize="none" spellcheck="false"></label><label for="mode">Match<select id="mode" name="mode"><option value="perfect">Perfect rhymes</option><option value="multi">Multisyllabic rhymes</option><option value="slant">Slant rhymes</option><option value="phrase">Multi-word rhymes</option><option value="endings">Phrase endings</option></select></label><button type="submit">Find rhymes</button></form><div class="examples"><span>Try:</span><button data-example="motion">motion</button><button data-example="writing">writing</button><button data-example="light">light</button><button data-example="ice cream" data-mode="phrase">ice cream · multi-word</button></div><p id="results-status" role="status" aria-live="polite">No account needed. Your word stays in this browser.</p><ul id="results" aria-label="Rhyme results" aria-busy="false"></ul></div></section>
 <section class="content"><h2>What counts as a multisyllabic rhyme?</h2><p>A multisyllabic rhyme matches sounds across two or more syllables. In this tool, “motion” and “ocean” match from the stressed vowel through the ending. “Light” and “night” are perfect rhymes with a one-syllable match, so they appear in Perfect rhymes.</p><p>A long word does not automatically make a multisyllabic rhyme. The length of the matching sound is what matters.</p></section>
 <section class="content"><h2>How to use the results</h2><p>Read the candidates out loud in your accent. Put the word back into your line and check both its meaning and rhythm. Results favour common English usage and closer sound matches, not artistic quality. Rare dictionary words remain searchable but are omitted from suggestions.</p><p>This free tool uses American English dictionary pronunciations. Vocabulary and usage-frequency filters reduce obscure entries and proper-name noise; they are not guarantees that every suggestion fits your line. Slant matches share vowel sounds with a close consonant-tail difference; they are deliberately selective. Multi-word rhymes compare two to four syllables across word boundaries, including close slants. Try “ice cream” or “insight”. Phrase endings match only the final word. Both search a small curated phrase bank, so coverage is limited. English is available now; other languages await source-clearance and language-quality checks. It does not cover every accent, slang word or phrase. The full Cadence app offers a broader writing workspace and additional rhyme modes.</p></section>
 <section class="content"><h2>Private searches, no sign-in</h2><p>The pronunciation dictionary loads on your first search. Matching happens in your browser; the tool does not send your word to a server or save it. The website host still receives ordinary requests for page and dictionary files.</p><p><a href="/cadence/search/THIRD-PARTY-NOTICES.txt">Dictionary source and licence</a> · <a href="/privacy">Privacy policy</a></p></section>`}
];
const artistSection = `<section class="artist-section" aria-labelledby="artist-heading"><div><h2 id="artist-heading">Your words.<br>Your way through.</h2><p>Tools for your writing. Not writing in your place.</p><p>Explore a rhyme, loop a beat, capture a take. You decide what belongs in the song. Transcription helps put your recorded words on the page; it is not a replacement for your voice.</p><a class="button" href="/cadence/">See the writing workspace</a></div><figure><img src="/assets/cadence/screens/rhyme-families.webp" alt="Real Cadence editor with rhyme highlighting and suggestions" loading="lazy" width="620" height="1348"><figcaption>Your lyric stays at the centre.</figcaption></figure></section>`;
const comparison = `<section class="content comparison"><h2>Choose the workspace for the stage you’re in.</h2><p>You may already have tools you love. Here’s where each kind fits—and where Cadence brings the steps together.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Writing workflow comparison"><table><caption>A workflow comparison, not a feature rating of individual products.</caption><thead><tr><th scope="col">Workspace</th><th scope="col">Use it for</th><th scope="col">Where Cadence fits</th></tr></thead><tbody><tr><th scope="row">A notes app</th><td>Getting an idea down quickly.</td><td>Keep the lyric with its beat, takes and rhyme exploration.</td></tr><tr><th scope="row">A rhyme dictionary</th><td>Looking for another sound or ending.</td><td>Explore suggestions beside the verse you’re writing.</td></tr><tr><th scope="row">A full production DAW</th><td>Detailed recording, production and mixing.</td><td>Build a mobile demo from the same song workspace. Export when you’re ready to take it further.</td></tr><tr><th scope="row">Cadence</th><td>Developing your words into a performance.</td><td>Lyrics, beat loops, vocal takes, arrangement and a mobile DAW together.</td></tr></tbody></table></div></section>`;
for (const page of pages) {
 page.body += (page.slug === 'songwriting-app' || page.slug === 'rap-writing-app' ? comparison : '') + artistSection;
 const url = `${domain}/cadence/${page.slug}/`;
 const schema = {'@context':'https://schema.org','@type':page.tool?'WebApplication':'WebPage',name:page.title,description:page.description,url,...(page.tool?{applicationCategory:'ReferenceApplication',operatingSystem:'Any modern web browser',offers:{'@type':'Offer',price:'0',priceCurrency:'GBP'}}:{})};
 const breadcrumb = {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Cadence',item:`${domain}/cadence/`},{'@type':'ListItem',position:2,name:page.title.split(' | ')[0],item:url}]};
 const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${domain}/assets/cadence/screens/library.webp"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#08090c"><link rel="icon" href="/assets/cadence/app-icon.webp"><link rel="stylesheet" href="/cadence/search/search.css"><script type="application/ld+json">${JSON.stringify([schema,breadcrumb])}</script>${page.tool?'<script type="module" src="/cadence/search/tool.mjs"></script>':''}<script type="module" src="/cadence/media-policy.js"></script></head>
<body><a class="skip" href="#main">Skip to content</a><header><div class="shell"><a class="brand" href="/cadence/"><picture aria-hidden="true"><source media="(prefers-reduced-motion: reduce)" srcset="/assets/cadence/cadence-mark-static.webp"><img src="/assets/cadence/cadence-mark.webp" data-animated-mark data-static-src="/assets/cadence/cadence-mark-static.webp" alt="" width="36" height="36"></picture>Cadence</a><nav aria-label="Main"><a href="/cadence/songwriting-app/">Songwriting</a><a href="/cadence/rhyme-finder/">Rhyme finder</a><a href="/cadence/#download">Get the app</a></nav></div></header>
<main class="shell" id="main"><div class="hero ${page.image?'':'text-only'}"><div><p class="crumb"><a href="/cadence/">Cadence</a> / ${page.tool?'Rhyme finder':'Songwriting resources'}</p><h1>${page.heading}</h1><p class="intro">${page.intro}</p>${page.tool?'':cta}</div>${page.image?`<figure class="shot"><img src="/assets/cadence/screens/${page.image}" alt="${escape(page.alt)}" width="620" height="1348"><figcaption>${page.alt}.</figcaption></figure>`:''}</div>${page.body}
<section class="content"><h2>Keep writing in Cadence</h2><p>Keep lyrics, rhyme ideas, beats and takes together as your song develops.</p>${cta}</section><section class="content"><h2>Explore your next step</h2><div class="related">${pages.filter(p=>p.slug!==page.slug).map(p=>`<a href="/cadence/${p.slug}/">${p.title.split(' | ')[0]}</a>`).join('')}</div></section></main><footer><div class="shell">Cadence by Brand Name Changes<nav aria-label="Footer"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/support">Support</a><a href="/cadence/feedback/">Send feedback</a></nav></div></footer></body></html>\n`;
 const enhanced = html.replace('</head>', '<script type="module" src="/cadence/search/atmosphere.mjs"></script></head>').replace('<body>', '<body><div class="atmosphere" aria-hidden="true"></div>');
 const directory=path.join(root,'cadence',page.slug); mkdirSync(directory,{recursive:true}); writeFileSync(path.join(directory,'index.html'),enhanced);
}
const routes=['/','/cadence/','/privacy','/terms','/support','/delete-account','/cadence/feedback/',...pages.map(p=>`/cadence/${p.slug}/`)];
writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.map(p=>`  <url><loc>${domain}${p}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Built ${pages.length} search pages and ${routes.length} sitemap entries.`);
